# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_locations.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('user_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_request_user_follow', to=settings.AUTH_USER_MODEL)),
                ('user_initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_request_user_initial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follows_user_follow', to=settings.AUTH_USER_MODEL)),
                ('user_initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follows_user_initial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
